from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
PKG=ROOT.parent

def req(x,msg):
    if not x: raise AssertionError(msg)
    print('PASS ',msg)

def main():
    app=(ROOT/'ui/app.py').read_text(encoding='utf-8')
    req('Max Research Agent · ONNX Factory' in app,'app version synchronized')
    req('APP_VERSION = "1.4.5"' in (ROOT/'ui/ui_launcher.py').read_text(),'launcher version synchronized')
    req('APP_VERSION = "1.4.5"' in (ROOT/'ui/ui_bootstrap.py').read_text(),'bootstrap version synchronized')
    req('v1.4.5' in (ROOT/'START_UI.cmd').read_text(),'START_UI version synchronized')
    req((PKG/'migration_tools/MIGRATE_LINEAGE_FROM_v0_7_1_R3.ps1').exists(),'R3 lineage migration exists')
    mig=(PKG/'migration_tools/MIGRATE_LINEAGE_FROM_v0_7_1_R3.ps1').read_text()
    req('legacy_v0_7_1_R3_readonly' in mig and 'NOT copied into active' in mig,'R3 migration archives old runtime lineage instead of mixing kernels')
    readme=(PKG/'README_FIRST.md').read_text()
    pm=json.loads((PKG/'governance/PACKAGE_MANIFEST.json').read_text(encoding='utf-8'))
    ca=json.loads((PKG/'governance/CURRENT_AUTHORITY.json').read_text(encoding='utf-8'))
    r5=json.loads((PKG/'governance/checkpoints/CHECKPOINT_PRE_STAGE11_STATUS.json').read_text(encoding='utf-8'))
    req((r5.get('cumulative_acceptance') or {}).get('passed')==96 and (r5.get('cumulative_acceptance') or {}).get('total')==96,'R5 historical checkpoint remains 96/96')
    req((pm.get('backend_e2e_audit') or {}).get('stage_1_10_status')=='CLOSED_EXACT_TREE','package manifest synchronized to Stage1-10 closure')
    req((pm.get('backend_e2e_audit') or {}).get('stage_11_status') in {'AUDIT_ACTIVE','CLOSED_EXACT_TREE'},'package manifest declares Stage11 release authority')
    req(ca.get('backend_stage_11_status') in {'AUDIT_ACTIVE','CLOSED_EXACT_TREE'},'CURRENT_AUTHORITY declares Stage11 release authority')
    local=ca.get('local_cumulative_acceptance') or {}
    pm_acc=pm.get('local_acceptance') or {}
    req(int(local.get('passed',-1))==136 and int(local.get('total',-1))==136 and local.get('first_failed_gate') is None,'CURRENT_AUTHORITY v1.4.5 cumulative target synchronized to 136/136 exact-tree source/contract closure')
    req(int(pm_acc.get('passed',-1))==int(local.get('passed',-2)) and int(pm_acc.get('total',-1))==int(local.get('total',-2)),'package/current cumulative acceptance counts synchronized')
    req(local.get('schema')=='MAX_BUILD_ACCEPTANCE_V56_MODEL_INSPECTOR_LIVE_RUNTIME_R1' and str(local.get('report','')).endswith('BUILD_ACCEPTANCE_v1_4_5.json'),'current acceptance schema/report synchronized')
    req((pm.get('kpi_by_gate_v077') or {}).get('research_h1_trades_per_month')==8 and (pm.get('kpi_by_gate_v077') or {}).get('strategy_optimizer_h1_trades_per_month')==20,'package KPI-by-gate sample baselines synchronized')
    req('93_OF_93' not in json.dumps(pm) and 'STAGE8_E2E_WORKFLOW_AUDIT' not in json.dumps(pm),'package manifest contains no stale Stage1-7/Stage8 authority')
    req(not any(str(x.get('status'))=='PASS' for x in (pm.get('external_gates') or []) if isinstance(x,dict)),'external gates are not promoted to PASS')
    req('Hardware profile → Model capability registry → LLM Research Director' in readme,'README R7 adaptive research route')
    req('v1.4.5' in readme and 'KPI by Gate' in readme and 'H1 baseline = **20 trades/month**' in readme and 'H1 = **8 trades/month**' in readme,'README v1.4.5 KPI/sample authority synchronized')
    req((ROOT/'docs'/'research'/'HARDWARE_ADAPTIVE_MODEL_RESEARCH_V1.md').exists(),'R7 adaptive architecture documented')
    arch=(ROOT/'docs'/'research'/'HARDWARE_ADAPTIVE_MODEL_RESEARCH_V1.md').read_text()
    req('hybrid::<temporal>::<policy>' in arch and 'PatchTST' in arch and 'iTransformer' in arch and 'TFT' in arch,'dynamic Transformer/hybrid architecture documented')
    req((ROOT/'docs'/'research'/'RESEARCH_WORKFLOW_V3.md').exists(),'Research Workflow V3 documented')
    req('CPCV opens as the same separate progressive finalist stage' in (ROOT/'docs'/'research'/'RESEARCH_WORKFLOW_V3.md').read_text(),'CPCV finalist-only authority documented')
    req((ROOT/'docs'/'research'/'RESEARCH_ENGINE_V3.md').exists(),'Scientific Research Engine V3 documented')
    rk=(ROOT/'docs'/'research'/'RESEARCH_KERNEL_V2.md').read_text(); req('TemporalIndexContract' in rk and 'Evaluation Vault' in rk,'Research Kernel V2 chronology documented')
    cfg=json.loads((ROOT/'config/config.json').read_text())
    req(cfg['champion_factory']['fresh_to_mode']=='AUTO_NEWEST','Forward AUTO_NEWEST')
    req(int(cfg['champion_factory']['monte_carlo_simulations'])==10000,'MC default 10000')
    req(cfg['compute']['mode']=='AUTO','Compute AUTO default')
    req(cfg['champion_factory'].get('orchestrator_enabled') is True,'Master Orchestrator enabled')
    req(str((cfg.get('research_architecture') or {}).get('mode'))=='SCIENTIST_HARDWARE_ADAPTIVE','hardware-adaptive research mode default')
    req(str((cfg.get('research_architecture') or {}).get('family_selection_mode'))=='SCIENTIST_DIRECTED','family selection defaults to Scientist-directed Owner allow-list')
    req(len((cfg.get('research_architecture') or {}).get('allowed_families') or [])>=11,'manual family checklist defaults include Transformer family expansion')
    req(str((cfg.get('research_architecture') or {}).get('capacity_governor'))=='EVIDENCE_AWARE_DYNAMIC_MODEL_CAPACITY_V3','evidence-aware dynamic capacity governor configured')
    req(abs(float((cfg.get('research_architecture') or {}).get('hybrid_priority',-1))-0.50)<1e-12,'topology priority defaults to 0.50')
    req('adaptive_hybrid_priority' in app and 'Single ↔ Hybrid' in app and 'Topology direction' in app and 'Scientist directed' in app,'topology slider UI synchronized')
    req(abs(float(((cfg.get('agent') or {}).get('search') or {}).get('scientific_creativity',-1))-0.50)<1e-12,'scientific creativity defaults to 0.50')
    req(abs(float(((cfg.get('agent') or {}).get('search') or {}).get('llm_research_influence',-1))-0.45)<1e-12,'LLM research influence configured explicitly')
    req('Scientific creativity' in app and 'LLM influence' in app and 'llm_research_influence' in app and 'Scientist temperature' not in app,'R13 creativity UI authority synchronized')
    fsp=(cfg.get('research_architecture') or {}).get('family_size_priorities') or {}
    req(len(fsp)>=11 and all(abs(float(v)-0.50)<1e-12 for v in fsp.values()),'R14 all base families default to neutral 0.50 size priority')
    req('Model size priority' in app and 'adaptive_size_priority_{fam}' in app and all(x in app for x in ('lightgbm','xgboost','random_forest','gru','lstm','tcn','transformer','patchtst','itransformer','tft','transformer_moe')),'R14 per-family size sliders visible')
    req('SEED_STABILITY' in ((cfg.get('agent') or {}).get('llm') or {}).get('hypothesis_kinds',[]),'R13 seed-stability hypothesis registered')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_3_R6.md').exists() and (PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_3_R6.md').exists(),'R6 historical authority retained')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_4_R2.md').exists(),'R7 R2 historical repair record retained')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R1.md').exists(),'R8 R1 capacity/MoE repair record exists')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R2.md').exists(),'R9 R2 Transformer-family repair record exists')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R3.md').exists() and (ROOT/'docs'/'contracts'/'TOPOLOGY_PRIORITY_DECISION_CONTRACT_V1.md').exists(),'R10 topology/decision-contract docs exist')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R4.md').exists() and (ROOT/'docs'/'contracts'/'DETERMINISTIC_DISCOVERY_PARITY_V1.md').exists(),'R12 deterministic Discovery parity docs exist')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R5.md').exists() and (ROOT/'docs'/'contracts'/'SCIENTIST_SUPERVISOR_CREATIVITY_PARITY_V1.md').exists(),'R13 Scientist/Supervisor creativity parity docs exist')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R6.md').exists() and (ROOT/'docs'/'research'/'MODEL_SIZE_PRIORITY_V1.md').exists(),'R14 per-family size-priority docs exist')
    req(all((ROOT/'docs'/'repairs'/x).exists() for x in ('REPAIR_v0_8_0.md','REPAIR_v0_8_1.md','REPAIR_v0_8_2.md','REPAIR_v0_8_3.md','REPAIR_v0_8_4.md','REPAIR_v0_8_5.md','REPAIR_v0_8_6.md','REPAIR_v0_8_7.md','REPAIR_v0_8_8.md','REPAIR_v0_8_9.md','REPAIR_v0_9_0.md','REPAIR_v0_9_1.md','REPAIR_v0_10_0.md','REPAIR_v0_11_0.md','REPAIR_v0_11_1.md','REPAIR_v0_11_2.md','REPAIR_v0_12_0.md','REPAIR_v0_12_1.md','REPAIR_v0_12_2.md','REPAIR_v0_12_3.md','REPAIR_v1_2_4.md','REPAIR_v1_2_5.md','REPAIR_v1_2_6.md','REPAIR_v1_3_0.md','REPAIR_v1_3_1.md','REPAIR_v1_3_2.md','REPAIR_v1_3_3.md','REPAIR_v1_3_4.md','REPAIR_v1_4_0.md','REPAIR_v1_4_1.md','REPAIR_v1_4_2.md','REPAIR_v1_4_3.md','REPAIR_v1_4_4.md','REPAIR_v1_4_5.md')),'repair lineage through v1.4.5 documented')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R6_REPAIR1.md').exists() and '70 / 70 PASS' in (ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R6_REPAIR1.md').read_text(),'R14 Repair1 hybrid/resource closure documented')
    req((PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_4_R2.md').exists(),'R7 R2 Owner runtime acceptance retained')
    req((PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_5_R1.md').exists(),'R8 R1 Owner runtime acceptance exists')
    req((PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_5_R2.md').exists(),'R9 R2 Owner runtime acceptance exists')
    req((PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_5_R3.md').exists(),'R10 R3 Owner runtime acceptance exists')
    req((PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_5_R4.md').exists(),'R12 R4 Owner runtime acceptance exists')
    req((PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_5_R5.md').exists(),'R13 R5 Owner runtime acceptance exists')
    req((PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_5_R6.md').exists(),'R14 R6 Owner runtime acceptance exists')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R6_REPAIR4.md').exists() and (PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_5_R6_REPAIR4.md').exists(),'R15 Repair4 data-quality/LLM-resilience docs exist')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R6_REPAIR5.md').exists() and (PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_5_R6_REPAIR5.md').exists(),'R15 Repair5 quote-gate correction docs exist')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R6_REPAIR6.md').exists() and (PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_5_R6_REPAIR6.md').exists(),'R16 Repair6 runtime-truth docs exist')
    req((ROOT/'docs'/'repairs'/'REPAIR_v0_7_5_R6_REPAIR7.md').exists() and (ROOT/'docs'/'ui'/'SCIENTIST_CHAT_READ_ONLY_V1.md').exists() and (PKG/'owner_acceptance/runtime/OWNER_RUNTIME_ACCEPTANCE_v0_7_5_R6_REPAIR7.md').exists(),'R17 Repair7 Scientist Chat docs exist')
    req((ROOT/'tests'/'scientist_chat_readonly_selftest.py').exists() and (ROOT/'tests'/'scientist_chat_ui_selftest.py').exists(),'R17 Scientist Chat acceptance tests exist')
    req((ROOT/'docs'/'research'/'RESEARCH_CONTROL_R1.md').exists(),'R19 Research Control R1 docs exist')
    req((ROOT/'docs'/'contracts'/'MANUAL_RESEARCH_V1.md').exists(),'R19 Manual Research V1 docs exist')
    req((ROOT/'docs'/'ui'/'SCIENTIST_CHAT_R2_STREAMING_CONTRACT.md').exists(),'R19 Scientist Chat R2 streaming docs exist')
    req((PKG/'governance/PROJECT_HANDOFF_CURRENT.md').exists() and (PKG/'governance/CONTRACT_AUDIT_INDEX.md').exists(),'R19 room-transfer authority docs exist')
    req((ROOT/'data/data_quality.py').exists() and (ROOT/'host/mt5_gap_repair.py').exists(),'R15 data-quality and MT5 gap-repair authority source exists')
    req('Data quality · MT5 broker reconciliation' in app and 'matching_mt5_gap_fill_targets' in app,'R15 latest Max UI exposes broker-aware data-quality repair')
    req('Max Research Agent — ONNX Factory' in readme,'README uses Max Research Agent ONNX Factory branding')
    for f in ('hybrid_capacity_envelope_parity_selftest.py','resource_preflight_selftest.py','family_size_priority_selftest.py','family_size_priority_e2e_selftest.py','creativity_parity_selftest.py','hybrid_ablation_runtime_selftest.py','seed_feedback_creativity_selftest.py','scientist_context_parity_selftest.py','deterministic_discovery_parity_selftest.py','cpcv_seed_confirmation_selftest.py','topology_priority_selftest.py','standalone_hybrid_decision_contract_selftest.py','transformer_family_expansion_selftest.py','transformer_family_capacity_selftest.py','transformer_family_hybrid_selftest.py','capacity_governor_selftest.py','transformer_moe_selftest.py','scientist_capacity_plan_selftest.py','moe_dynamic_hybrid_selftest.py','hardware_adaptive_research_selftest.py','family_compute_control_selftest.py','temporal_family_selftest.py','dynamic_hybrid_selftest.py','llm_quota_provenance_selftest.py','r7_adaptive_ui_selftest.py'):
        req((ROOT/'tests'/f).exists(),f'R7 selftest registered: {f}')
    req(len(cfg['agent']['llm'].get('fallback_on',[]))>=4,'LLM transient/quota fallback policy configured')
    req(cfg['agent']['llm'].get('model_health_enabled') is True,'persistent model health enabled')
    ra=(ROOT/'acceptance/runners/run_acceptance.py').read_text(encoding='utf-8')
    for f in ('research_mode_authority_selftest.py','manual_research_contract_selftest.py','manual_orchestrator_selftest.py','scientist_chat_streaming_selftest.py','v078_strategy_optimizer_repair_selftest.py','v081_strategy_optimizer_atomic_resume_selftest.py','v082_optimizer_ui_scientist_recovery_selftest.py','v085_strategy_geometry_sync_selftest.py','v085_weighted_r_optimizer_selftest.py','v086_optimizer_history_rebuild_selftest.py','v087_research_strategy_boundary_overall_mean_r_selftest.py'):
        req(f in ra,f'R19 selftest registered: {f}')
    req('v089_optimizer_cache_frame_recovery_selftest.py' in ra,'R33 v0.8.9 cache/frame recovery selftest registered')
    req('v090_champion_tester_preset_sync_selftest.py' in ra,'R34 v0.9.0 Champion Tester preset sync selftest registered')
    req('v091_gap_repair_tester_selftest.py' in ra,'R35 v0.9.1 MT5 gap-repair launch selftest registered')
    req('v0111_data_quality_staged_repair_selftest.py' in ra,'R39 staged Data Quality repair selftest registered')
    req('v012_research_e2e_workflow_selftest.py' in ra and 'v0121_e2e_forward_local_dq_selftest.py' in ra,'R41/R42 v0.12.x Golden E2E selftests registered')
    req('v0122_e2e_promotion_diagnostics_selftest.py' in ra and (ROOT/'tools/research/RUN_RESEARCH_E2E.cmd').exists(),'R43 v1.2.4 E2E promotion diagnostics + one-click CMD registered')
    req('v0123_challenger_page_evidence_parity_selftest.py' in ra,'R44 v0.12.3 evidence-parity regression retained')
    req('v124_strategy_model_page_separation_e2e_audit_selftest.py' in ra,'R45 v1.2.4 Strategy/Model page separation + E2E audit regression retained')
    req('v125_strategy_champion_kpi_evidence_selftest.py' in ra and 'v126_authority_lifecycle_governance_selftest.py' in ra and 'v130_langgraph_architecture_selftest.py' in ra and 'v130_agentic_scientist_contract_selftest.py' in ra and 'v131_cuda_authority_selftest.py' in ra and 'v132_scientific_workflow_repair_selftest.py' in ra and 'v133_challenger_retention_lifecycle_selftest.py' in ra and 'v134_cvar_legacy_migration_selftest.py' in ra and 'v140_agentic_learning_foundation_selftest.py' in ra and 'v141_agentic_learning_audit_repair_selftest.py' in ra and 'v142_model_size_advisor_ui_selftest.py' in ra and 'v143_strategy_navigation_lifecycle_selftest.py' in ra and 'v144_kpi_ui_full_authority_selftest.py' in ra and 'v145_model_inspector_live_runtime_selftest.py' in ra,'R46-R59 preservation + v1.3.x/v1.4.x regressions registered')
    req('v091_onnx_audit_ui_selftest.py' in ra,'R36 v0.9.1 ONNX family/trade-audit/terminal-UI selftest registered')
    req('v010_challenger_lifecycle_selftest.py' in ra and 'v011_strategy_challenger_lifecycle_selftest.py' in ra,'R37/R38 Model + Strategy Challenger lifecycle selftests registered')
    print('RELEASE_SYNC_SELFTEST PASS')
if __name__=='__main__': main()
