from __future__ import annotations
from pathlib import Path

MODELLAB_ROOT = Path(__file__).resolve().parents[1]
APP_DIR = MODELLAB_ROOT
PACKAGE_ROOT = MODELLAB_ROOT.parent
CONFIG_DIR = MODELLAB_ROOT / "config"
REQUIREMENTS_DIR = MODELLAB_ROOT / "requirements"
ACCEPTANCE_DIR = MODELLAB_ROOT / "acceptance"
PROJECT_NAME = "Max MTF"
PROJECT_VERSION = "2.0.1"
EA_VERSION = "2.00"
EA_ROOT = PACKAGE_ROOT / "EA_v2_00"
EA_BASELINE_DIR = EA_ROOT / "baseline"
EA_CHALLENGERS_DIR = EA_ROOT / "challengers"
EA_ARCHIVE_DIR = EA_ROOT / "archive"
EA_SOURCE = EA_BASELINE_DIR / "Max_MTF.mq5"
MODELS_ROOT = PACKAGE_ROOT / "Models"
MODEL_BASELINE_DIR = MODELS_ROOT / "baseline"
MODEL_CHALLENGERS_DIR = MODELS_ROOT / "challengers"
MODEL_ARCHIVE_DIR = MODELS_ROOT / "archive"
RELEASES_ROOT = PACKAGE_ROOT / "Releases"
RELEASE_ACTIVE_DIR = RELEASES_ROOT / "active"
RELEASE_CHALLENGERS_DIR = RELEASES_ROOT / "challengers"
RELEASE_ARCHIVE_DIR = RELEASES_ROOT / "archive"
LEGACY_SINGLE_TF_REFERENCE = PACKAGE_ROOT / "EA_v1_06"
DATA_ROOT = PACKAGE_ROOT / "Data" / "MTF"
MTF_NATIVE_DIR = DATA_ROOT / "native"
MTF_BUNDLES_DIR = DATA_ROOT / "bundles"

def ensure_project_layout() -> None:
    for p in (EA_BASELINE_DIR, EA_CHALLENGERS_DIR, EA_ARCHIVE_DIR, MODEL_BASELINE_DIR, MODEL_CHALLENGERS_DIR, MODEL_ARCHIVE_DIR, RELEASE_ACTIVE_DIR, RELEASE_CHALLENGERS_DIR, RELEASE_ARCHIVE_DIR, MTF_NATIVE_DIR, MTF_BUNDLES_DIR):
        p.mkdir(parents=True, exist_ok=True)
